### ISSUE TITLE
Version 3.0 - Import error using python versions < 3.7

### ISSUE THREAD

**Issue by davidlouis** [docusign/docusign-esign-python-client#44]
Using python 3.6.7:
`from docusign_esign import ApiClient`

The following error occurs originating from line 24 of `models/account_settings_information.py`
`SyntaxError: more than 255 arguments`

I note the README still states the required python version is 2.7+

Was this was an oversight in updating the readme, or do plan to continue to support for these python versions? 

NOTE: Version 2.1 of the docusign-python-client doesn't have this problem

**Comment by Craigk0001** [comment]
I ran into this one too! Perhaps turn the args into a list of args?
It seems python <3.7 limits the args that can be on a function to 255.
https://stackoverflow.com/questions/26766076/pass-more-than-255-arguments-to-a-function

**Comment by harsharahul** [comment]
Hi @Craigk0001 ,
We are aware of this limitation with the Python version 3> and <3.7. The design of the API model classes is currently like this. We will look into the matter and see how the model initialization can be handled for specific versions. 
Meanwhile I suggest you to use Python version >=3.7 or Python 2*

-Harsha

**Comment by WilliamWCYoung** [comment]
I have proposed a solution, using Python's kwargs functionality. It keeps faithful to the existing solution by only setting variables that we have defined for Swagger.

If it's liked, I'll make the changes across the codebase.

**Comment by Krowemoh** [comment]
We were able to get around this bug by copying over a newer version of models/account_settings_information.py. 

It seems to be working perfectly now, hopefully we didn't clobber anything!

**Comment by deadbeef404** [comment]
It might be a good idea to set the [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) section of `setup.py` to prevent the package being installed on older Python versions, removing confusion. :)

**Comment by harsharahul** [comment]
This is corrected from Version 3.1.0+
Thank you all for your suggestions and contribution.

**Comment by anujism** [comment]
@harsharahul This has appeared again in 3.2.0.

**Comment by seanfagan** [comment]
This is still broken in latest version. Will there be a more permanent fix? Python 3.6 is supported until the end of 2021.

**Comment by harsharahul** [comment]
Hi folks, sorry for the trouble. This has been fixed again from v3.8.1+
